#!/usr/bin/env bash
# Write a Bash script that displays a list of currently running processes.

echo "PID   PPID  USER     STAT  %CPU %MEM COMMAND"
# Use ps to display processes, including those without a TTY, in a tree-like format
ps axo pid,ppid,user,stat,%cpu,%mem,command --forest

