#!/bin/bash

kill_process() {
  pid=$(pgrep -f "6-stop_me_if_you_can")
  if [ -n "$pid" ]; then
    echo "Killing process with PID $pid"
    kill -TERM "$pid"
  else
    echo "Process not found"
  fi
}


