#!/usr/bin/env bash
# Script
# Check if username argument is provided
if [ $# -ne 1 ]; then
    echo "Usage: $0 <username>"
    exit 1
fi

username=$1

# Check if the user exists
if ! id "$username" &>/dev/null; then
    echo "User $username does not exist."
    exit 1
fi

# Run whoami command under the specified user
sudo -u "$username" whoami
