#!/usr/bin/env bash
#This is the Script

sudo service nginx stop
echo -e "\nuser nginx;" >> /etc/nginx/nginx.conf
chmod 644 /etc/nginx/nginx.conf
sed -i 's/listen 80;/listen 8080;/g' /etc/nginx/sites-available/default
pkill apache2
sudo service nginx restart

