#!/usr/bin/env bash
#This is the Script

sudo service ngnix stop
echo "user ngnix"; >> /etc/ngnix/ngnix.conf
chmod 644 /etc/ngnix/ngnix.conf
sed -i 's/80/8080/g' /etc/ngnix/sites-available/default
pkill apache2
sudo service ngnix restart
