#!/usr/bin/env bash
# gunicorn reload

pgrep gunicorn | xargs -r kill -HUP 
# restart
sudo systemctl daemon-reload
sudo systemctl start gunicorn
sudo systemctl enable gunicorn
sudo systemctl status gunicorn
sudo systemctl restart gunicorn
