#!/usr/bin/env bash
# Find the PID of the Gunicorn master process
MASTER_PID=$(ps aux | grep '[g]unicorn' | awk '{print $2}')
# Gracefully reload Gunicorn
kill -HUP $MASTER_PID
echo "Gunicorn reloaded gracefully."
